dist: xenial
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7
# blocklist branches
branches:
  except:
  - requires-io-master
  - /^dependabot.*$/
install:
- pip install -r requirements-test.txt
- pip install .[babel] coveralls wheel
script:
- py.test -v --cov pyramid_localize tests/
after_success:
    - coveralls
jobs:
  include:
  - stage: linters
    python: 3.7
    install:
    - pip install -r requirements-lint.txt
    - pip install .[tests]
    script:
    - pycodestyle
    - pydocstyle
    - pylint pyramid_localize tests
    after_success: skip
  - stage: deploy
    python: 3.7
    if: tag IS present
    script: skip
    deploy:
      provider: pypi
      user: fizyk
      password:
        secure: DwNZeHXX6sLDVUZpRGy866jP1IuScKOqrYdQ3FmceDn2bRVfH3ebMzVQJLlOlqVizuR+SxhJ0W+/gfWdGxog2dDpEquUolNXx8S85I1GQaoUqqrMt8z9LqLIYjtgumMUczVvnWc7tQ0GFKrmQzjXxVfBxaFSjwB5BBgmWJXE+UY=
      on:
        tags: true
        repo: fizyk/pyramid_localize
      distributions: bdist_wheel
