name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.4.1
    with:
      cover_package: pyramid_localize
      python-versions: '["3.8", "3.9", "3.10", "3.11"]'
      pipenv: true
      pipenv-install-options: "--skip-lock"